 export const countryTopCities = {
    India: ["Pune", "Mumbai", "Delhi", "Bangalore"],
    USA: ["New York", "Los Angeles", "Chicago", "Houston"],
    China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"],
    Japan: ["Tokyo", "Osaka", "Nagoya", "Sapporo"],
    Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
    UnitedKingdom: ["London", "Birmingham", "Manchester", "Glasgow"],
    France: ["Paris", "Lyon", "Marseille", "Toulouse"],
    Brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
    Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
    Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
    Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
    Italy: ["Rome", "Milan", "Naples", "Turin"],
    SouthKorea: ["Seoul", "Busan", "Incheon", "Daegu"],
    Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Tijuana"],
    SouthAfrica: ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
    Spain: ["Madrid", "Barcelona", "Valencia", "Seville"],
    Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa"],
    Indonesia: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    SaudiArabia: ["Riyadh", "Jeddah", "Mecca", "Medina"],
    Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
  };

  export const countriesDropdownOptions = [
    { "label": "India", "value": "India" },
    { "label": "USA", "value": "USA" },
    { "label": "China", "value": "China" },
    { "label": "Japan", "value": "Japan" },
    { "label": "Germany", "value": "Germany" },
    { "label": "United Kingdom", "value": "UnitedKingdom" },
    { "label": "France", "value": "France" },
    { "label": "Brazil", "value": "Brazil" },
    { "label": "Russia", "value": "Russia" },
    { "label": "Australia", "value": "Australia" },
    { "label": "Canada", "value": "Canada" },
    { "label": "Italy", "value": "Italy" },
    { "label": "South Korea", "value": "SouthKorea" },
    { "label": "Mexico", "value": "Mexico" },
    { "label": "South Africa", "value": "SouthAfrica" },
    { "label": "Spain", "value": "Spain" },
    { "label": "Turkey", "value": "Turkey" },
    { "label": "Indonesia", "value": "Indonesia" },
    { "label": "Saudi Arabia", "value": "SaudiArabia" },
    { "label": "Argentina", "value": "Argentina" }
  ];
  
  
